 # 一、ndarray
 ## 1.ndarray的特性
 多维性


In [1]:
import numpy as np

In [2]:
arr = np.array(5) # 创建0维的ndarray数组
print(arr)
print('arr的维度: ',arr.ndim) # 数组的number of dimensions

5
arr的维度:  0


In [3]:
arr = np.array([1, 2, 3]) # 创建1维的ndarray数组
print(arr)
print('arr的维度: ',arr.ndim) # 数组的number of dimensions

[1 2 3]
arr的维度:  1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 创建1维的ndarray数组
print(arr)
print('arr的维度: ',arr.ndim) # 数组的number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度:  2


# 同质性

In [5]:
arr = np.array([1, 'hello']) # 不同数据类型的数据强制转化为相同类型数据
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 'hello']) # 不同数据类型的数据强制转化为相同类型数据
print(arr)

['1' 'hello']


# 2.ndarray的属性

In [7]:
arr = np.array(1)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

1
()
0
1
int64


In [8]:
arr = np.array([1, 2.5, 3])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

[1.  2.5 3. ]
(3,)
1
3
float64
[1.  2.5 3. ]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
[[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [10]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1,dtype=np.float64)
print(arr.ndim) # 属性
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr) # 元素跟原始的数组相同，但是不是一个数组
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((3,4),dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


In [13]:
arr = np.zeros((200,),dtype=int)
print(arr)
print(arr.dtype)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
int64


In [14]:
# 全1
arr = np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [15]:
# 未初始化
arr = np.empty((4,2))
print(arr)

[[4.67296746e-307 1.69121096e-306]
 [1.33511290e-306 6.23058368e-307]
 [2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588061e-307]]


In [16]:
arr = np.full((3, 4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [17]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      2290391382408                  64                   0
                    0]
 [7307484471542939648 7306353938258933561 3977304309530440501
  3919316086870389816]
 [3702352743075505465 3544956562670969141 7292227429981054514
  7004563302398701879]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [18]:
# 等差数列
arr = np.arange(1,51,1)  # 开始，结束（不包含），步长
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [19]:
# 等间隔数列
arr = np.linspace(0, 100, 5) # 包含end 分成5份，4个间隔
print(arr)

[  0.  25.  50.  75. 100.]


In [20]:
arr = np.linspace(0, 100, 5,dtype=int) # 包含end 分成5份，4个间隔
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr = np.logspace(0, 4, 5,base=2) # 包含end结束
print(arr)

[ 1.  2.  4.  8. 16.]


In [22]:
# 特殊矩阵
# 单位矩阵：主对角线上的元素为1，其他的数字为0
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [23]:
# 对角矩阵:主对角线上非零的数字，其他的数字为0
arr = np.diag([5, 1, 2, 3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [24]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)

[[0.06132176 0.45304193 0.91306419]
 [0.18097989 0.58711328 0.85628897]]


In [25]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6,(2, 3))
print(arr)

[[3.24309779 3.76541137 4.19515548]
 [5.85624679 3.44027691 3.34178515]]


In [26]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30,(2, 3))
print(arr)

[[22  7 17]
 [27 22  9]]


In [27]:
# 生成随机数列（正态分布）（-3到+3之间）
# 两边概率小，中间概率大
arr = np.random.randn(10, 5)
print(arr)

[[-0.23108997  0.09099617 -0.06642399  0.10434058  1.02507059]
 [-0.21244213 -0.52176392 -0.45581873 -0.31677826 -1.17185695]
 [ 0.39123008 -0.98367726  0.40585162 -0.78773026 -0.20663878]
 [ 0.12300578  1.682733    1.10153763 -0.04717083 -0.51938926]
 [ 1.22868026  0.63844882  0.93670252 -0.18184348 -1.02361851]
 [ 0.05375183 -0.3461296   1.95022404  0.60545188  0.41450446]
 [-0.11528537 -0.21550035  0.91958207  1.54314776  1.0178775 ]
 [-2.09464865  0.77711144 -0.79875699 -1.66229083  1.38444426]
 [-0.98019769  1.21528183 -0.57379829  0.47502873 -0.24408989]
 [-1.24433678  0.92399323 -0.08997183  0.98437373  0.42482211]]


In [28]:
# 设置随机种子
np.random.seed(42)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[7 4 8 5 7]
 [3 7 8 5 4]]


4. ndarray的数据类型

布尔类型 bool

整数类型 int uint

浮点数 float

复数 complex

In [29]:
arr = np.array([1, 0, 2, 0], dtype='bool') # 非0为true np.bool
print(arr)

[ True False  True False]


In [30]:
arr = np.array([-128, 0, 127, 0], dtype='int8') #int8[-128,127]
print(arr)

[-128    0  127    0]


5.切片和索引

In [31]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)

[24  3 22 53  2 88 30 38  2 64 60 21 33 76 58 22 89 49 91 59]


In [32]:
print(arr[10])
print(arr[:]) # 获取全部数据
print(arr[2: 5]) # 左闭右开 start:end+1
print(arr[slice(2,15, 3)]) # start, end, step
print(arr[(arr>50) & (arr<70)])# 布尔索引

60
[24  3 22 53  2 88 30 38  2 64 60 21 33 76 58 22 89 49 91 59]
[22 53  2]
[22 88  2 21 58]
[53 64 60 58 59]


In [33]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4,8))
print(arr)

[[42 92 60 80 15 62 62 47]
 [62 51 55 64  3 51  7 21]
 [73 39 18  4 89 60 14  9]
 [90 53  2 84 92 60 71 44]]


In [34]:
print(arr[1, 3])
print(arr[1, 2:5])
print(arr[2] [arr[2]>50]) # 行
print(arr[:,3] [arr[:,3]>50]) # 列

64
[55 64  3]
[73 89 60]
[80 64 84]


5.ndarray的运算

In [35]:
# 算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a +b)
print(a -b)
print(a *b)
print(a /b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [36]:
c = [1, 2, 3]
d = [4, 5, 6]
for i in range(len(c)):
    d[i] = d[i] + (c[i])
print(d)

[5, 7, 9]


In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a +b)
print(a -b)
print(a *b)
print(a /b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [38]:
# 数组与标量的算数运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [39]:
# 广播机制
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(a + b)
print(b - a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [40]:
# 矩阵的运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)


[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 2.3 numpy中的常用函数
## 1. 基本的数学函数

In [41]:
import numpy as np


In [42]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [43]:
# 计算指数 e的x次方 e**x = y
print(np.exp(0))

1.0


In [44]:
# 计算自然对数 lnx的值 lny = x
print(np.log(2.71))

0.9969486348916096


In [45]:
# 计算三角函数正弦、余弦
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [46]:
# 计算绝对值
arr = np.array([-1, 1 , 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [47]:
# 计算a的b次方   a    b
print(np.power(arr, 3))

[ -1   1   8 -27]


In [48]:
# 四舍五入
print(np.round([3.2, 4.5, 8.1 , 9.6]))

[ 3.  4.  8. 10.]


In [49]:
# 向上和向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))


[ 2. 26. 82.]
[ 1. 25. 81.]


In [50]:
# 检测缺失值NaN
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

2.统计函数

求和、平均值、中位数、标准差、方差

最大值、最小值

分位数、累积和、累积差

In [51]:
arr = np.random.randint(1,20,8)
print(arr)

[ 8 15  3 14 17  4 18  8]


In [52]:
# 求和
print(np.sum([1, 2, 3]))

6


In [53]:
# 计算平均值
print(np.mean([1, 2, 3]))


2.0


In [54]:
# 计算中位数
print(np.median([1, 2, 3, 4, 5]))
print(np.median([1, 2, 4, 4, 4, 4, 6]))

3.0
4.0


In [55]:
# 计算标准差、方差
# 1 2 3的平均值 = 2
# 每一个数跟平均值的差的平方的平均值 = 方差
print(np.var([1, 2, 3, 4, 5])) # var = 方差
print(np.std([1, 2, 3, 4, 5])) # std = 标准差
print(np.var(arr))

2.0
1.4142135623730951
30.109375


In [56]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))


[ 8 15  3 14 17  4 18  8]
18 6
3 2


In [57]:
# 分位数
# 中位数是第五十个的百分位数
# 1       2       3
print(np.median([1, 2, 3, 4, 5]))
print(np.median([1, 2, 3, 4]))
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
print(np.median(arr))
print(np.percentile(arr, 25)) # 25%分位数
print(np.percentile(arr, 50)) # 50%分位数

3.0
2.5
[44 47 64 67]
55.5


46.25
55.5


In [58]:
# 累积和、累积极
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr)) 
print(np.cumsum(arr))
print(np.prod(arr))
print(np.cumprod(arr))

15
[ 1  3  6 10 15]
120
[  1   2   6  24 120]


## 比较函数

是否大于、等于、小于

逻辑：与、或、非

检查数组中是否有一个True，是否所有都为True，自定义条件


In [ ]:
# 是否大于
print(np.greater([3,4, 5, 6, 7], 4)) # 是否大于
print(np.less([3,4, 5, 6, 7], 4)) # 是否小于
print(np.equal([3,4, 5, 6, 7], 4))  # 是否等于
print(np.equal([3,4, 5],[4, 4, 4]))  # 格式相同

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]


In [67]:
# 与或非
print(np.logical_and([0, 0], [1, 1]))
print(np.logical_or([0, 0], [1, 0]))
print(np.logical_not([1, 0]))

[False False]
[ True False]
[False  True]


In [69]:
# 检查元素是否至少有一个元素为True
print(np.any([0, 1,0 ,1 ,0]))
# 检查元素是否全是为True
print(np.all([0, 1, 0, 1, 0]))

True
False


In [ ]:
# 精密条件
# print(np.where(条件，符合条件，不符合条件))
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr<3, arr, 0))

[1 2 0 0 0]


In [73]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr<3, 1, 0))

[1 1 0 0 0]


In [74]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(score>=60, '及格', '不及格'))

[53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
['不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [75]:
print(np.where(
    score<60, '不及格',np.where(
        score<80, '良好','优秀'
        
    )
))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [76]:
# np.select(条件，返回的结果)
print(np.select([score>80, (score>60) & (score<=80),score<60], 
                ['youxiu', 'lianghao', 'bujige'],
                default='未知'))

['bujige' 'youxiu' 'bujige' 'lianghao' 'lianghao' 'youxiu' 'lianghao'
 'bujige' 'lianghao' 'lianghao' 'lianghao' 'bujige' 'youxiu' 'youxiu'
 'lianghao' 'youxiu' 'lianghao' 'lianghao' 'youxiu' 'lianghao']


In [80]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
print(np.sort(arr))
print(np.argsort(arr)) # 返回排序后的索引
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [81]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [82]:
# 两个数组的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate([arr1, arr2]))


[1 2 3 4 5 6]


In [ ]:
# 数组的切割
print(np.split(arr, [6, 12, 18])) 

[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [89]:
# 调整数组的形状
print(np.reshape(arr, [2, 10]))

[[45 48 65 68 68 10 84 22 37 88]
 [71 89 89 13 59 66 40 88 47 89]]


In [103]:
# 28 30 29 31 32 30 29
import numpy as np
data = np.array([28, 30, 29, 31, 32, 30, 29])
print(data)
print('平均气温：', '%.3f'%np.mean(data))
print('最高气温：', np.max(data))
print('最低气温: ', np.min(data))
print('气温超过30的天数: ',len(data[data>30]))
print(np.cumsum(np.where(data>30, 1, 0))[-1])
print(np.count_nonzero(data>30)) # 统计非零元素的个数

[28 30 29 31 32 30 29]
平均气温： 29.857
最高气温： 32
最低气温:  28
气温超过30的天数:  2
2
2


In [113]:
# 85 90 78 92 88
score = np.array([85, 90, 78, 92, 88])
print(score)
print(np.sort(score))
print('平均分： ', '%.3f'%np.mean(score))
print('中位数： ', np.median(score))
print('标准差： ', '%.3f'%np.std(score))
print('十分制： ', score/10)

[85 90 78 92 88]
[78 85 88 90 92]
平均分：  86.600
中位数：  88.0
标准差：  4.883
十分制：  [8.5 9.  7.8 9.2 8.8]


In [116]:
# A = [[1, 2], [3,4]]和B = [[5, 6], [7, 8]]
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)
print(A * B)
print(A @ B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [126]:
# 生成一个(3，4)的随机整数数组，范围[0，10)
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print('每一列最大值： ', np.max(arr, axis=0))  # 0=列， 1=行
print('每一行最小值： ', np.min(arr, axis=1))  # 0=列， 1=行  
print('替换为-1: ', f"\n{np.where(arr%2==1, -1, arr)}")
arr[arr%2==1] = -1
print(arr) 

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每一列最大值：  [7 9 7 6]
每一行最小值：  [0 3 2]
替换为-1:  
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
# 数组变形
#创建一个1到12的一维数组，并转换为(3，4)的二维数组。
#计算每行的和与每列的平均值。
#将数组展平为一维数组。
arr = np.array(range(1, 13))
print(arr)
print(arr.reshape(3, 4))
print('sum in line: ', np.sum(arr.reshape(3, 4), axis=1))
print('sum in column: ', np.sum(arr.reshape(3, 4), axis=0))
print('mean in column: ', np.mean(arr.reshape(3, 4), axis=0))
print('flatten: ', arr.reshape(3, 4).flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum in line:  [10 26 42]
sum in column:  [15 18 21 24]
mean in column:  [5. 6. 7. 8.]
flatten:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [135]:
#生成一个(5，5)的随机数组，范围[0，20)。
#找出数组中大于10的元素。
#将所有大于10 的元素替换为0。
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr>10])
arr[arr>10] = 0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [141]:
# 6个月的销售额(万元)为 [120,135,110,125,130,140]。
#销售额的总和、均值和方差。
#找出销售额最高的月份和最低的月份
money = np.array([120,135,110,125,130,140])
print('sum: ', np.sum(money))
print(np.mean(money))
print(np.var(money))
print('max: ', np.argmax(money)+1)
print('min: ', np.argmin(money)+1)

sum:  760
126.66666666666667
97.22222222222223
max:  6
min:  3


In [147]:
#给定A=[1,2,3]和B=[4,5,6].
#将A和B水平拼接为一个新数组。
#将A和B垂直拼接为一个新数组。
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1, arr2])
print(arr3)
print(np.reshape(arr3,(2, 3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [157]:
# 给定数组 [2,1,2,3,1,4,3].
# 找出数组中的唯一值并排序。
# 计算每个唯一值出现的次数。
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))
u_arr,counts = np.unique(arr,return_counts=True)
print(u_arr)
print(counts)
d = []
for i in range(len(u_arr)):
    d = d+[len(arr[arr==u_arr[i]])]
print(d)

[1 2 3 4]
[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


In [168]:
# 某商店5天的销售额(万元)和成本(万元)如下:
# 销售额:[20,25,22,30,28]
# 成本:[15, 18, 16,22, 20]
# 计算每天的利润(销售额-成本)。
# 计算利润的平均值和标准差。
# 找出利润最高的天数。
money = np.array([20,25,22,30,28])
cost = np.array([15, 18, 16,22, 20])
profit = money -cost
print(profit)
print(np.mean(profit))
print(np.std(profit))
max_profit = np.max(profit)
max_days = np.where(profit ==max_profit)[0] +1
print(f"最高利润是：{max_profit}, 出现在：{max_days}天")

[5 7 6 8 8]
6.8
1.16619037896906
最高利润是：8, 出现在：[4 5]天
